# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setEnabled(True)
        TabWidget.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)
        TabWidget.setMinimumSize(QtCore.QSize(600, 400))
        TabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../assets/bionic-leg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.setWindowIcon(icon)
        TabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background-color: rgb(245, 245, 245);\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"    background-color: rgb(191,191,191);\n"
"     padding: 1em 1.5em; /* Ajoute un espace intérieur autour du texte */\n"
"\n"
"    margin: 0 1px 0 0;\n"
"    color: black;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(4,19,245);\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background-color: rgb(211, 211, 211); \n"
"    cursor: pointer;\n"
"}")
        TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        TabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        TabWidget.setIconSize(QtCore.QSize(16, 16))
        TabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        TabWidget.setUsesScrollButtons(False)
        TabWidget.setDocumentMode(False)
        TabWidget.setTabsClosable(False)
        TabWidget.setMovable(True)
        TabWidget.setTabBarAutoHide(True)
        self.RobotOperation = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RobotOperation.sizePolicy().hasHeightForWidth())
        self.RobotOperation.setSizePolicy(sizePolicy)
        self.RobotOperation.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.RobotOperation.setStyleSheet("QWidget{\n"
"background-color: rgb(239, 239, 239);\n"
"\n"
"}")
        self.RobotOperation.setObjectName("RobotOperation")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.RobotOperation)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftCol = QtWidgets.QWidget(self.RobotOperation)
        self.LeftCol.setStyleSheet("QWidget{\n"
" background-color: none;\n"
"border: none\n"
"}")
        self.LeftCol.setObjectName("LeftCol")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LeftCol)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.animatio_widget = QtWidgets.QWidget(self.LeftCol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animatio_widget.sizePolicy().hasHeightForWidth())
        self.animatio_widget.setSizePolicy(sizePolicy)
        self.animatio_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(211, 211, 211)\n"
"\n"
"}")
        self.animatio_widget.setObjectName("animatio_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.animatio_widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SagittalPlane = QtWidgets.QLabel(self.animatio_widget)
        self.SagittalPlane.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"   padding-left: 5px\n"
"\n"
"}")
        self.SagittalPlane.setObjectName("SagittalPlane")
        self.verticalLayout_2.addWidget(self.SagittalPlane)
        self.FrontalPlane = QtWidgets.QLabel(self.animatio_widget)
        self.FrontalPlane.setStyleSheet("QLabel{\n"
"\n"
"border: none\n"
"}")
        self.FrontalPlane.setText("")
        self.FrontalPlane.setObjectName("FrontalPlane")
        self.verticalLayout_2.addWidget(self.FrontalPlane)
        self.animation_walking1 = QtWidgets.QLabel(self.animatio_widget)
        self.animation_walking1.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"   padding-left: 5px\n"
"\n"
"\n"
"}")
        self.animation_walking1.setObjectName("animation_walking1")
        self.verticalLayout_2.addWidget(self.animation_walking1)
        self.animation_walking2 = QtWidgets.QLabel(self.animatio_widget)
        self.animation_walking2.setStyleSheet("QLabel{\n"
"\n"
"border: none\n"
"\n"
"}")
        self.animation_walking2.setText("")
        self.animation_walking2.setObjectName("animation_walking2")
        self.verticalLayout_2.addWidget(self.animation_walking2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 3)
        self.verticalLayout.addWidget(self.animatio_widget)
        self.foot_widget_1 = QtWidgets.QWidget(self.LeftCol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foot_widget_1.sizePolicy().hasHeightForWidth())
        self.foot_widget_1.setSizePolicy(sizePolicy)
        self.foot_widget_1.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(211, 211, 211)\n"
"\n"
"}")
        self.foot_widget_1.setObjectName("foot_widget_1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.foot_widget_1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_27 = QtWidgets.QLabel(self.foot_widget_1)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_8.addWidget(self.label_27)
        self.verticalLayout.addWidget(self.foot_widget_1)
        self.button1 = QtWidgets.QWidget(self.LeftCol)
        self.button1.setStyleSheet("QWidget{\n"
" background-color: blue;\n"
"border: 1px solid black\n"
"}")
        self.button1.setObjectName("button1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.button1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.button1)
        self.pushButton.setStyleSheet("QPushButton{\n"
" color: white;\n"
" border : none;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.button1)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.LeftCol)
        self.MiddleCol = QtWidgets.QWidget(self.RobotOperation)
        self.MiddleCol.setStyleSheet("QWidget{\n"
" background-color: none;\n"
"border: none\n"
"}")
        self.MiddleCol.setObjectName("MiddleCol")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MiddleCol)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.battery_widget = QtWidgets.QWidget(self.MiddleCol)
        self.battery_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(211, 211, 211)\n"
"\n"
"}")
        self.battery_widget.setObjectName("battery_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.battery_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.battery_level = QtWidgets.QLabel(self.battery_widget)
        self.battery_level.setStyleSheet("QLabel{\n"
"\n"
"border: none\n"
"\n"
"}")
        self.battery_level.setObjectName("battery_level")
        self.horizontalLayout_4.addWidget(self.battery_level)
        self.progressBar = QtWidgets.QProgressBar(self.battery_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"font-weight: bold;\n"
"\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_3.addWidget(self.battery_widget)
        self.time_widget = QtWidgets.QWidget(self.MiddleCol)
        self.time_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(211, 211, 211)\n"
"\n"
"}")
        self.time_widget.setObjectName("time_widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.time_widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.time_widget)
        self.label_2.setStyleSheet("QLabel{\n"
"\n"
"border: none\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label_usage_time = QtWidgets.QLabel(self.time_widget)
        self.label_usage_time.setStyleSheet("QLabel{\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"border: none\n"
"\n"
"\n"
"}")
        self.label_usage_time.setObjectName("label_usage_time")
        self.horizontalLayout_5.addWidget(self.label_usage_time)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.verticalLayout_3.addWidget(self.time_widget)
        self.driver_info_widget = QtWidgets.QWidget(self.MiddleCol)
        self.driver_info_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(211, 211, 211);\n"
"\n"
"}")
        self.driver_info_widget.setObjectName("driver_info_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.driver_info_widget)
        self.verticalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.driver_info_widget)
        self.label.setStyleSheet("QLabel{\n"
"border:none;\n"
"\n"
"\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_12 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_12.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.widget_12)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.label_20 = QtWidgets.QLabel(self.widget_12)
        self.label_20.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
" \n"
" font-weight: bold;\n"
"}")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_11.addWidget(self.label_20)
        self.gridLayout_2.addWidget(self.widget_12, 2, 1, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_14.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.widget_14)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.label_24 = QtWidgets.QLabel(self.widget_14)
        self.label_24.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"\n"
" font-weight: bold;\n"
"}")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_15.addWidget(self.label_24)
        self.gridLayout_2.addWidget(self.widget_14, 4, 1, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_15.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.widget_15)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.label_26 = QtWidgets.QLabel(self.widget_15)
        self.label_26.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
" \n"
" font-weight: bold;\n"
"}")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_16.addWidget(self.label_26)
        self.gridLayout_2.addWidget(self.widget_15, 5, 1, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_13.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.widget_13)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.label_22 = QtWidgets.QLabel(self.widget_13)
        self.label_22.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"\n"
" font-weight: bold;\n"
"}")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.gridLayout_2.addWidget(self.widget_13, 3, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.driver_info_widget)
        self.widget.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("")
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setStyleSheet("QLabel{\n"
"    border: none;\n"
"    background-color: rgb(230, 230, 230);\n"
"    font-weight: bold;\n"
"\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_3.setStyleSheet("QWidget{\n"
"border:none\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.label_17 = QtWidgets.QLabel(self.widget_3)
        self.label_17.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"\n"
" font-weight: bold;\n"
"}")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.gridLayout_2.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_2.setStyleSheet("QWidget{\n"
"border:none\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"\n"
" font-weight: bold;\n"
"}")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_8.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.label_23 = QtWidgets.QLabel(self.widget_8)
        self.label_23.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"  \n"
" font-weight: bold;\n"
"}")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_14.addWidget(self.label_23)
        self.gridLayout_2.addWidget(self.widget_8, 4, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_5.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"\n"
" font-weight: bold;\n"
"}")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.gridLayout_2.addWidget(self.widget_5, 2, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_7.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.label_21 = QtWidgets.QLabel(self.widget_7)
        self.label_21.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"\n"
" font-weight: bold;\n"
"}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        self.gridLayout_2.addWidget(self.widget_7, 3, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_4.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.label_18 = QtWidgets.QLabel(self.widget_4)
        self.label_18.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"  \n"
" font-weight: bold;\n"
"}")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.gridLayout_2.addWidget(self.widget_4, 1, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.driver_info_widget)
        self.widget_9.setStyleSheet("QWidget{\n"
"border:none\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.widget_9)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.label_25 = QtWidgets.QLabel(self.widget_9)
        self.label_25.setStyleSheet("QLabel{\n"
"    border: none;\n"
"   background-color: rgb(230, 230, 230);\n"
"  \n"
" font-weight: bold;\n"
"}")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.gridLayout_2.addWidget(self.widget_9, 5, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.driver_info_widget)
        self.widget_19 = QtWidgets.QWidget(self.MiddleCol)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_3.addWidget(self.widget_19)
        self.widget_6 = QtWidgets.QWidget(self.MiddleCol)
        self.widget_6.setStyleSheet("QWidget{\n"
" background-color: blue;\n"
"border: 1px solid black\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
" color: white;\n"
" border : none;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 5)
        self.verticalLayout_3.setStretch(2, 50)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 4)
        self.horizontalLayout.addWidget(self.MiddleCol)
        self.RightCol = QtWidgets.QWidget(self.RobotOperation)
        self.RightCol.setStyleSheet("QWidget{\n"
"background-color: none;\n"
"border: none\n"
"    \n"
"}")
        self.RightCol.setObjectName("RightCol")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.RightCol)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_10 = QtWidgets.QWidget(self.RightCol)
        self.widget_10.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(211, 211, 211)\n"
"\n"
"}")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_28 = QtWidgets.QLabel(self.widget_10)
        self.label_28.setStyleSheet("QLabel{\n"
" border : none;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"}")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.status_label = QtWidgets.QLabel(self.widget_10)
        self.status_label.setStyleSheet("QLabel{\n"
"\n"
"font-weight: bold;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_6.addWidget(self.status_label)
        self.verticalLayout_18.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.RightCol)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_21 = QtWidgets.QWidget(self.widget_11)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_23.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.widget_24 = QtWidgets.QWidget(self.widget_21)
        self.widget_24.setStyleSheet("QWidget{\n"
" background-color: blue;\n"
"border: none\n"
"\n"
"}")
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
" color: white;\n"
" border : none;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_26.addWidget(self.pushButton_5)
        self.verticalLayout_23.addWidget(self.widget_24)
        self.label_30 = QtWidgets.QLabel(self.widget_21)
        self.label_30.setStyleSheet("QLabel{\n"
" \n"
"    background-color: rgb(211,211,255);\n"
"color: white;\n"
"border: none;\n"
"font-weight: bold\n"
"\n"
"\n"
"}")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_23.addWidget(self.label_30)
        self.verticalLayout_23.setStretch(0, 2)
        self.verticalLayout_23.setStretch(1, 1)
        self.horizontalLayout_9.addWidget(self.widget_21)
        self.widget_22 = QtWidgets.QWidget(self.widget_11)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_24.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_25 = QtWidgets.QWidget(self.widget_22)
        self.widget_25.setStyleSheet("QWidget{\n"
" background-color: blue;\n"
"border: none\n"
"\n"
"}")
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
" color: white;\n"
" border : none;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_27.addWidget(self.pushButton_6)
        self.verticalLayout_24.addWidget(self.widget_25)
        self.label_31 = QtWidgets.QLabel(self.widget_22)
        self.label_31.setStyleSheet("QLabel{\n"
" \n"
"    background-color: rgb(211,211,255);\n"
"color: white;\n"
"border: none;\n"
"font-weight: bold\n"
"\n"
"\n"
"}")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_24.addWidget(self.label_31)
        self.verticalLayout_24.setStretch(0, 2)
        self.verticalLayout_24.setStretch(1, 1)
        self.horizontalLayout_9.addWidget(self.widget_22)
        self.widget_23 = QtWidgets.QWidget(self.widget_11)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_25.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_26 = QtWidgets.QWidget(self.widget_23)
        self.widget_26.setStyleSheet("QWidget{\n"
" background-color: blue;\n"
"border: none\n"
"\n"
"}")
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
" color: white;\n"
" border : none;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_28.addWidget(self.pushButton_7)
        self.verticalLayout_25.addWidget(self.widget_26)
        self.label_32 = QtWidgets.QLabel(self.widget_23)
        self.label_32.setStyleSheet("QLabel{\n"
" \n"
"    background-color: rgb(211,211,255);\n"
"color: white;\n"
"border: none;\n"
"font-weight: bold\n"
"\n"
"\n"
"}")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_25.addWidget(self.label_32)
        self.verticalLayout_25.setStretch(0, 2)
        self.verticalLayout_25.setStretch(1, 1)
        self.horizontalLayout_9.addWidget(self.widget_23)
        self.verticalLayout_18.addWidget(self.widget_11)
        self.widget_16 = QtWidgets.QWidget(self.RightCol)
        self.widget_16.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(211, 211, 211);\n"
"\n"
"}")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_21.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_29 = QtWidgets.QLabel(self.widget_16)
        self.label_29.setStyleSheet("QLabel{\n"
" border : none;\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"}")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_21.addWidget(self.label_29)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_16)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"border: 1px solid black\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 211, 147))
        self.scrollAreaWidgetContents.setStyleSheet("QWidget{\n"
"border: none}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setStyleSheet("QScrollArea{\n"
"    color: white;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none\n"
"\n"
"\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 211, 147))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_29.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_29.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_29.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_29.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_29.addWidget(self.label_37)
        self.verticalLayout_29.setStretch(0, 1)
        self.verticalLayout_29.setStretch(1, 1)
        self.verticalLayout_29.setStretch(2, 1)
        self.verticalLayout_29.setStretch(3, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_22.addWidget(self.scrollArea_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_21.addWidget(self.scrollArea)
        self.verticalLayout_18.addWidget(self.widget_16)
        self.widget_20 = QtWidgets.QWidget(self.RightCol)
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_18.addWidget(self.widget_20)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_17 = QtWidgets.QWidget(self.RightCol)
        self.widget_17.setStyleSheet("QWidget{\n"
" background-color: blue;\n"
"border: 1px solid black\n"
"}")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_17)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
" color: white;\n"
" border : none;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_20.addWidget(self.pushButton_4)
        self.horizontalLayout_7.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.RightCol)
        self.widget_18.setStyleSheet("QWidget{\n"
" background-color: blue;\n"
"border: 1px solid black\n"
"}")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_18)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
" color: white;\n"
" border : none;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_19.addWidget(self.pushButton_3)
        self.horizontalLayout_7.addWidget(self.widget_18)
        self.verticalLayout_18.addLayout(self.horizontalLayout_7)
        self.verticalLayout_18.setStretch(0, 10)
        self.verticalLayout_18.setStretch(1, 20)
        self.verticalLayout_18.setStretch(2, 60)
        self.verticalLayout_18.setStretch(3, 1)
        self.verticalLayout_18.setStretch(4, 6)
        self.horizontalLayout.addWidget(self.RightCol)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 3)
        TabWidget.addTab(self.RobotOperation, "")
        self.TurnandDebug = QtWidgets.QWidget()
        self.TurnandDebug.setObjectName("TurnandDebug")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.TurnandDebug)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_38 = QtWidgets.QLabel(self.TurnandDebug)
        self.label_38.setStyleSheet("QLabel{\n"
"\n"
"font-size: 32px\n"
"\n"
"}")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_10.addWidget(self.label_38)
        TabWidget.addTab(self.TurnandDebug, "")
        self.DataCheck = QtWidgets.QWidget()
        self.DataCheck.setObjectName("DataCheck")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.DataCheck)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_39 = QtWidgets.QLabel(self.DataCheck)
        self.label_39.setStyleSheet("QLabel{\n"
"\n"
"font-size: 32px\n"
"\n"
"}")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_11.addWidget(self.label_39)
        TabWidget.addTab(self.DataCheck, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        TabWidget.addTab(self.tab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "AM - GUI"))
        self.SagittalPlane.setText(_translate("TabWidget", "Sagittal Plane"))
        self.animation_walking1.setText(_translate("TabWidget", "Frontal Plane"))
        self.label_27.setText(_translate("TabWidget", "TextLabel"))
        self.pushButton.setText(_translate("TabWidget", "Force Quit"))
        self.battery_level.setText(_translate("TabWidget", "Battery Level :"))
        self.label_2.setText(_translate("TabWidget", "Usage Time : "))
        self.label_usage_time.setText(_translate("TabWidget", "-"))
        self.label.setText(_translate("TabWidget", "Current amount & temperature for each driver"))
        self.label_7.setText(_translate("TabWidget", "RH_Flex"))
        self.label_20.setText(_translate("TabWidget", "- / -"))
        self.label_12.setText(_translate("TabWidget", "RA_Lat"))
        self.label_24.setText(_translate("TabWidget", "- / -"))
        self.label_15.setText(_translate("TabWidget", "RA_Med"))
        self.label_26.setText(_translate("TabWidget", "- / -"))
        self.label_10.setText(_translate("TabWidget", "RK"))
        self.label_22.setText(_translate("TabWidget", "- / -"))
        self.label_3.setText(_translate("TabWidget", "LH_Abd"))
        self.label_13.setText(_translate("TabWidget", "- / -"))
        self.label_5.setText(_translate("TabWidget", "LH_Rot"))
        self.label_17.setText(_translate("TabWidget", "- / -"))
        self.label_4.setText(_translate("TabWidget", "RH_Abd"))
        self.label_16.setText(_translate("TabWidget", "- / -"))
        self.label_11.setText(_translate("TabWidget", "LA_Lat"))
        self.label_23.setText(_translate("TabWidget", "- / -"))
        self.label_8.setText(_translate("TabWidget", "LH_Flex"))
        self.label_19.setText(_translate("TabWidget", "- / -"))
        self.label_9.setText(_translate("TabWidget", "LK"))
        self.label_21.setText(_translate("TabWidget", "- / -"))
        self.label_6.setText(_translate("TabWidget", "RH_Rot"))
        self.label_18.setText(_translate("TabWidget", "- / -"))
        self.label_14.setText(_translate("TabWidget", "LA_Med"))
        self.label_25.setText(_translate("TabWidget", "- / -"))
        self.pushButton_2.setText(_translate("TabWidget", "Output limit [100]%"))
        self.label_28.setText(_translate("TabWidget", "Current State"))
        self.status_label.setText(_translate("TabWidget", "Offline"))
        self.pushButton_5.setText(_translate("TabWidget", "PushButton"))
        self.label_30.setText(_translate("TabWidget", "TextLabel"))
        self.pushButton_6.setText(_translate("TabWidget", "PushButton"))
        self.label_31.setText(_translate("TabWidget", "TextLabel"))
        self.pushButton_7.setText(_translate("TabWidget", "PushButton"))
        self.label_32.setText(_translate("TabWidget", "TextLabel"))
        self.label_29.setText(_translate("TabWidget", "Fault Detection"))
        self.label_33.setText(_translate("TabWidget", "Sensor fault 1: LH Inc Encoder error"))
        self.label_34.setText(_translate("TabWidget", "."))
        self.label_35.setText(_translate("TabWidget", "."))
        self.label_36.setText(_translate("TabWidget", "."))
        self.pushButton_4.setText(_translate("TabWidget", "End data storage"))
        self.pushButton_3.setText(_translate("TabWidget", "Stamp"))
        TabWidget.setTabText(TabWidget.indexOf(self.RobotOperation), _translate("TabWidget", "Robot Operation"))
        self.label_38.setText(_translate("TabWidget", "Page2"))
        TabWidget.setTabText(TabWidget.indexOf(self.TurnandDebug), _translate("TabWidget", "Turn and Debug"))
        self.label_39.setText(_translate("TabWidget", "Page 3"))
        TabWidget.setTabText(TabWidget.indexOf(self.DataCheck), _translate("TabWidget", "Data Check"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Exit"))
