# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(457, 296)
        Dialog.setMinimumSize(QtCore.QSize(457, 296))
        Dialog.setMaximumSize(QtCore.QSize(457, 296))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../assets/bionic-leg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QPushButton {\n"
"    background-color: rgb(24, 0, 255); \n"
"    border-radius: 1px;\n"
"    height: 35px;\n"
"    width: 130px;\n"
"    color: white;\n"
"    text-align: center; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 85, 255); \n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 281, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../assets/angela-removebg-preview.png"))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 180, 132, 86))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StartButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout.addWidget(self.StartButton)
        self.QuitButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.QuitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuitButton.setMouseTracking(False)
        self.QuitButton.setObjectName("QuitButton")
        self.verticalLayout.addWidget(self.QuitButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AM - GUI"))
        self.StartButton.setText(_translate("Dialog", "Start"))
        self.QuitButton.setText(_translate("Dialog", "Quit"))
