from PyQt5 import QtWidgets, uic, QtCore
from PyQt5.QtCore import pyqtSignal

class ExitWindow(QtWidgets.QDialog):
    """
    Custom QDialog window for displaying an exit prompt with a timer.

    Signals:
        window_closed: Signal emitted when the window is closed.

    Attributes:
        active (bool): Flag indicating if the window is active.
        is_showed (bool): Flag indicating if the window has been shown.

    Methods:
        __init__(): Initializes the ExitWindow instance.
        startAPP(): Starts the application and sets `active` to False.
        activate_close_event(): Activates the close event, emits `window_closed` signal.
        closeEvent(event): Manages the close event based on the `active` flag.
    """

    window_closed = pyqtSignal()

    def __init__(self):
        """
        Initializes the ExitWindow instance.

        Sets up the UI using a .ui file, sets a fixed size, and starts a QTimer to close
        the window automatically after 2 seconds.

        """
        super(ExitWindow, self).__init__()

        self.active = True  # Window is initially active
        self.is_showed = False  # Window is initially not shown

        # Load UI file generated by Qt Designer
        uic.loadUi('views/ui/exitwindow.ui', self)

        # Set fixed size for the dialog window
        self.setFixedSize(450, 300)

        # Start a QTimer to close the window after 2 seconds
        self.timer = QtCore.QTimer(self)
        self.timer.setSingleShot(True)
        self.timer.timeout.connect(self.activate_close_event)
        self.timer.start(2000)  # 2000 milliseconds = 2 seconds

    def startAPP(self):
        """
        Starts the application and sets `active` flag to False.

        Typically used to initiate the application's main functionalities.

        """
        self.run_serv()  # Placeholder method to start application services
        self.active = False  # Set active flag to False indicating application start

    def activate_close_event(self):
        """
        Activates the close event of the window.

        Sets `active` to False, closes the window, and emits the `window_closed` signal.

        """
        self.active = False  # Set active flag to False indicating window is closing
        self.close()  # Close the window
        self.window_closed.emit()  # Emit the signal before closing

    def closeEvent(self, event):
        """
        Manages the close event of the window.

        Ignores the close event if `active` flag is True (window is active).
        Otherwise, calls the base class method to handle the close event.

        :param event: Close event object.
        """
        if self.active:
            event.ignore()  # Ignore the close event if window is active
        else:
            super(ExitWindow, self).closeEvent(event)  # Call base class method to close the window
